## IMPORT REQUIRED LIBRARIES 📚

In [230]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from tabulate import tabulate 

pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.max_colwidth = None

# Visualization settings
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("Paired")
%matplotlib inline

## Data Loading  💽

In [231]:
try:
   df = pd.read_csv('data/AmazonSaleReport.csv', sep=',')
   print('- Data loaded ✅')
except:
    print('- Error data loading ❌')

- Data loaded ✅

/tmp/ipykernel_10371/1754567427.py:2: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/AmazonSaleReport.csv', sep=',')

---

In [232]:
print(f"\n📈 Dataset shape: {df.shape}")
print(f"📋 Columns: {list(df.columns)}")

📈 Dataset shape: (128975, 24)
📋 Columns: ['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

In [233]:
print('===== First 5 row =====')
df.head()

===== First 5 row =====

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,"Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal Merchant AAT-QX3UCCJESKPA2,Amazon PLCC Free-Financing Universal Merchant AAT-5QQ7BIYYQEDN2,Amazon PLCC Free-Financing Universal Merchant AAT-DSJ2QRXXWXVMQ,Amazon PLCC Free-Financing Universal Merchant AAT-CXJHMC2YJUK76,Amazon PLCC Free-Financing Universal Merchant AAT-CC4FAVTYR4X7C,Amazon PLCC Free-Financing Universal Merchant AAT-XXRCW6NZEPZI4,Amazon PLCC Free-Financing Universal Merchant AAT-CXNSLNBROFDW4,Amazon PLCC Free-Financing Universal Merchant AAT-R7GXNZWISTRFA,Amazon PLCC Free-Financing Universal Merchant AAT-WSJLDN3X7KEMO,Amazon PLCC Free-Financing Universal Merchant AAT-VL6FGQVGQVXUS,Amazon PLCC Free-Financing Universal Merchant AAT-EOKPWFWYW7Y6I,Amazon PLCC Free-Financing Universal Merchant AAT-ZYL5UPUNW6T62,Amazon PLCC Free-Financing Universal Merchant AAT-XVPICCHRWDCAI,Amazon PLCC Free-Financing Universal Merchant AAT-ETXQ3XXWMRXBG,Amazon PLCC Free-Financing Universal Merchant AAT-7X3XCTYG64VBE,Amazon PLCC Free-Financing Universal Merchant AAT-7CHGD3WTS3MHM,Amazon PLCC Free-Financing Universal Merchant AAT-26ZDKNME27X42,Amazon PLCC Free-Financing Universal Merchant AAT-4ZF5KN6E4LJK4,Amazon PLCC Free-Financing Universal Merchant AAT-7RCXIKUAX7DDY,Amazon PLCC Free-Financing Universal Merchant AAT-BRSZZ45H6MHAO,Amazon PLCC Free-Financing Universal Merchant AAT-MKLXOOZWQL7GO,Amazon PLCC Free-Financing Universal Merchant AAT-CB7UNXEXGIJTC,Amazon PLCC Free-Financing Universal Merchant #MP-gzasho-1593152694811,Amazon PLCC Free-Financing Universal Merchant AAT-WLBA4GZ52EAH4",False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [234]:
print('===== last 5 row =====')
df.tail()

===== last 5 row =====

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,Shipped,1,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,B09VC6KHX8,Shipped,1,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,Shipped,1,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,B0894Y2NJQ,Shipped,1,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,B0894X27FC,Shipped,1,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

---

## Initial Inspection 🔎

In [235]:
print("📊 DATASET INFORMATION:")
print("="*40)
df.info()

📊 DATASET INFORMATION:
========================================
<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

In [236]:
missing_data = df.isnull().sum()
missing_percent = (missing_data / len(df)) * 100
missing_value = pd.DataFrame({
    'Missing Data': missing_data,
    'Missing Percent': missing_percent
})
print('Missing value ❌')
print('='*40)
missing_value

Missing value ❌
========================================

                    Missing Data  Missing Percent
index                          0         0.000000
Order ID                       0         0.000000
Date                           0         0.000000
Status                         0         0.000000
Fulfilment                     0         0.000000
Sales Channel                  0         0.000000
ship-service-level             0         0.000000
Style                          0         0.000000
SKU                            0         0.000000
Category                       0         0.000000
Size                           0         0.000000
ASIN                           0         0.000000
Courier Status              6872         5.328164
Qty                            0         0.000000
currency                    7795         6.043807
Amount                      7795         6.043807
ship-city                     33         0.025586
ship-state                    33         0.025586
ship-postal-code              33         0.025586
ship-country                  33         0.025586
promotion-ids              49153        38.110487
B2B                            0         0.000000
fulfilled-by               89698        69.546811
Unnamed: 22                49050        38.030626

---

# Cleaning🧹

In [237]:
shape_before = df.shape
print(f'Number of rows and columns before cleaning: {df.shape}')

Number of rows and columns before cleaning: (128975, 24)

## Cleaning missing values in column Courier Status

In [238]:
df['Courier Status'].unique()

<StringArray>
[nan, 'Shipped', 'Cancelled', 'Unshipped']
Length: 4, dtype: str

In [239]:
df.loc[df["Courier Status"].isna(), "Status"].value_counts()

Status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [240]:
df.loc[
    (df["Courier Status"].isna()) & 
    (df["Status"] == "Cancelled"),
    "Courier Status"
] = "Cancelled"

In [241]:
df.shape

(128975, 24)

In [242]:
missing_courier_rows = df[
    (df["Courier Status"].isna()) &
    (df["Status"] != "Cancelled")
]
missing_courier_rows.shape

(11, 24)

In [243]:
df = df.drop(missing_courier_rows.index)

In [244]:
df.shape

(128964, 24)

- Delete 11 rows from the data

## Cleaning missing values in columns currency & Amount

In [245]:
df["currency"] = df["currency"].fillna("unknown")
df["Amount"] = df["Amount"].fillna(0)

In [246]:
print(f'Number of NaN values in column currency: {df['currency'].isna().sum()}')
print(f'Number of NaN values in column Amount: {df['Amount'].isna().sum()}')

Number of NaN values in column currency: 0
Number of NaN values in column Amount: 0

## Cleaning missing values in columns ship-city & ship-state & ship-postal-code & ship-country

In [247]:
print(f'Number of NaNs before cleaning: {df["ship-city"].isna().sum()}')

Number of NaNs before cleaning: 33

In [248]:
df = df.dropna(subset=["ship-city"])

In [249]:
print(f'Number of NaNs after cleaning: {df["ship-city"].isna().sum()}')

Number of NaNs after cleaning: 0

## Cleaning missing values in column promotion-ids

In [250]:
print(f'Number of NaNs before cleaning: {df["promotion-ids"].isna().sum()}')

Number of NaNs before cleaning: 49134

In [251]:
df["promotion-ids"] = df["promotion-ids"].fillna("No Promotion")

In [252]:
print(f'Number of NaNs after cleaning: {df["promotion-ids"].isna().sum()}')

Number of NaNs after cleaning: 0

## Cleaning missing values in columns fulfilled-by & Unnamed: 22

In [253]:
print(f'Number of NaNs before cleaning: {df.shape}')

Number of NaNs before cleaning: (128931, 24)

In [254]:
df = df.drop(columns=["fulfilled-by", "Unnamed: 22"])

In [255]:
print(f'Number of NaNs after cleaning: {df.shape}')

Number of NaNs after cleaning: (128931, 22)

In [256]:
shape_after = df.shape
print(f'Number of rows and columns after cleaning: {df.shape}')

Number of rows and columns after cleaning: (128931, 22)

In [257]:
print(f'Number of rows and columns deleted from the database: {[shape_before[0] - shape_after[0], shape_before[1] - shape_after[1]]}')

Number of rows and columns deleted from the database: [44, 2]

## Data cleanup is complete and 44 rows and 2 columns have been deleted.

---

## Casting Data 🔁

In [258]:
df = df.drop(columns=["index"])

In [259]:
# تبدیل تاریخ
df["Date"] = pd.to_datetime(df["Date"])

# کد پستی به string
df["ship-postal-code"] = (
    df["ship-postal-code"]
    .astype("Int64")
    .astype("string")
)

# ستون‌های categorical
categorical_columns = [
    "Status",
    "Fulfilment",
    "Sales Channel ",
    "ship-service-level",
    "Category",
    "Size",
    "currency",
    "ship-country",
    "ship-state"
]

for col in categorical_columns:
    df[col] = df[col].astype("category")

/tmp/ipykernel_10371/532942947.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])

In [260]:
df.info()

<class 'pandas.DataFrame'>
Index: 128931 entries, 0 to 128974
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128931 non-null  str
 1   Date                128931 non-null  datetime64[us]
 2   Status              128931 non-null  category
 3   Fulfilment          128931 non-null  category
 4   Sales Channel       128931 non-null  category
 5   ship-service-level  128931 non-null  category
 6   Style               128931 non-null  str
 7   SKU                 128931 non-null  str
 8   Category            128931 non-null  category
 9   Size                128931 non-null  category
 10  ASIN                128931 non-null  str
 11  Courier Status      128931 non-null  str
 12  Qty                 128931 non-null  int64
 13  currency            128931 non-null  category
 14  Amount              128931 non-null  float64
 15  ship-city           128931 non-null  str
 16  ship-state          128931 non-null  category
 17  ship-postal-code    128931 non-null  string
 18  ship-country        128931 non-null  category
 19  promotion-ids       128931 non-null  str
 20  B2B                 128931 non-null  bool
dtypes: bool(1), category(9), datetime64[us](1), float64(1), int64(1), str(7), string(1)
memory usage: 13.0 MB

- ### Performed data cleaning, handled missing values, removed unnecessary columns, and applied proper data type casting for AmazonSaleReport dataset.

---

### 1. What was the total sales amount?

In [288]:
total_revenue = df["Amount"].sum()
total_orders = df["Order ID"].nunique()
total_quantity = df["Qty"].sum()

sales_summary = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Total Quantity Sold"
    ],
    "Value": [
        f"{total_revenue:,.2f}",
        f"{total_orders:,}",
        f"{total_quantity:,}"
    ]
}, index=range(1, 4))


sales_summary

                Metric          Value
1        Total Revenue  78,574,007.30
2         Total Orders        120,350
3  Total Quantity Sold        116,621

### 2. How has sales changed over time?

In [286]:
monthly_sales = (
    df.groupby(df["Date"].dt.to_period("M"), observed=True)
    .agg(
        Revenue=("Amount", "sum"),
        Quantity_Sold=("Qty", "sum")
    )
    .reset_index()
)

monthly_sales["Month"] = monthly_sales["Date"].astype(str)

monthly_sales["Revenue_Change"] = monthly_sales["Revenue"].diff()

monthly_sales["Revenue_Change_%"] = (
    monthly_sales["Revenue"].pct_change() * 100
)

monthly_sales["Sales_Trend"] = monthly_sales["Revenue_Change"].apply(
    lambda x: (
        "Increase" if x > 0
        else "Decrease" if x < 0
        else "No Change"
    )
)

monthly_sales = monthly_sales[
    [
        "Month",
        "Revenue",
        "Quantity_Sold",
        "Revenue_Change",
        "Revenue_Change_%",
        "Sales_Trend"
    ]
]

monthly_sales["Revenue"] = monthly_sales["Revenue"].map(
    lambda x: f"{x:,.2f}"
)

monthly_sales["Quantity_Sold"] = monthly_sales["Quantity_Sold"].map(
    lambda x: f"{x:,}"
)

monthly_sales["Revenue_Change"] = monthly_sales["Revenue_Change"].map(
    lambda x: f"{x:,.2f}" if pd.notna(x) else "-"
)

monthly_sales["Revenue_Change_%"] = monthly_sales["Revenue_Change_%"].map(
    lambda x: f"{x:,.2f}%" if pd.notna(x) else "-"
)

monthly_sales.index = range(1, len(monthly_sales) + 1)

monthly_sales

,Month,Revenue,Quantity_Sold,Revenue_Change,Revenue_Change_%,Sales_Trend
1,2022-03,"101,683.85",156,-,-,No Change
2,2022-04,"28,831,249.32","44,196","28,729,565.47","28,253.81%",Increase
3,2022-05,"26,219,850.75","38,000","-2,611,398.57",-9.06%,Decrease
4,2022-06,"23,421,223.38","34,269","-2,798,627.37",-10.67%,Decrease

### 3. What is the average order value?

In [ ]:
total_revenue = df["Amount"].sum()
total_orders = df["Order ID"].nunique()

average_order_value = total_revenue / total_orders

aov_summary = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Average Order Value"
    ],
    "Value": [
        f"{total_revenue:,.2f}",
        f"{total_orders:,}",
        f"{average_order_value:,.2f}"
    ]
}, index=range(1, 4))

aov_summary

                Metric          Value
1        Total Revenue  78,574,007.30
2         Total Orders        120,350
3  Average Order Value         652.88

### 4. Which days recorded the highest sales?

In [292]:
top_sales_days = (
    df.groupby(df["Date"].dt.date)
    .agg(
        Revenue=("Amount", "sum"),
        Quantity_Sold=("Qty", "sum"),
        Orders=("Order ID", "nunique")
    )
    .reset_index()
    .rename(columns={"Date": "Day"})
    .sort_values("Revenue", ascending=False)
    .head(15)
)

top_sales_days["Revenue"] = top_sales_days["Revenue"].map(
    lambda x: f"{x:,.2f}"
)

top_sales_days["Quantity_Sold"] = top_sales_days["Quantity_Sold"].map(
    lambda x: f"{x:,}"
)

top_sales_days["Orders"] = top_sales_days["Orders"].map(
    lambda x: f"{x:,}"
)

top_sales_days.index = range(1, len(top_sales_days) + 1)

top_sales_days

           Day       Revenue Quantity_Sold Orders
1   2022-05-04  1,208,509.17         1,809  1,894
2   2022-05-03  1,190,672.59         1,863  1,941
3   2022-05-02  1,172,327.06         1,889  1,906
4   2022-04-14  1,113,487.56         1,695  1,754
5   2022-04-23  1,092,882.62         1,664  1,697
6   2022-04-20  1,091,550.41         1,695  1,708
7   2022-04-24  1,082,483.95         1,628  1,698
8   2022-05-01  1,079,957.52         1,661  1,663
9   2022-04-10  1,075,234.03         1,619  1,646
10  2022-04-15  1,024,143.13         1,619  1,732
11  2022-04-08  1,017,857.61         1,519  1,569
12  2022-04-03  1,011,763.38         1,544  1,565
13  2022-04-16  1,009,402.23         1,537  1,612
14  2022-06-05    989,093.03         1,452  1,474
15  2022-04-22    977,653.62         1,499  1,552